In [2]:
import numpy as np
 # Create and display zero , one , and n- dimensional arrays
zero_dim_array = np . array (5)
one_dim_array = np . array ([1 , 2 , 3])
n_dim_array = np . array ([[1 , 2] , [3 , 4]])
for arr in [ zero_dim_array , one_dim_array , n_dim_array ]:
    print(f" Array :\n{arr }\ nDimension : {arr. ndim }\ nData type :{arr. dtype }\n")

 Array :
5\ nDimension : 0\ nData type :int64

 Array :
[1 2 3]\ nDimension : 1\ nData type :int64

 Array :
[[1 2]
 [3 4]]\ nDimension : 2\ nData type :int64



In [ ]:
import numpy as np
# Create arrays of different dimensions
array_0d = np . array (5)
array_1d = np . array ([1 , 2 , 3 , 4 , 5])
array_2d = np . array ([[1 , 2 , 3] , [4 , 5 , 6]])
array_3d = np . array ([[[1 , 2] , [3 , 4]] , [[5 , 6] , [7 ,8]]])
 # Print arrays with shapes
for i , arr in enumerate ([ array_0d , array_1d , array_2d ,array_3d ]) :
     print ( f"{i}D Array :\n{arr }\ nShape : {arr. shape }\n")

0D Array :
5\ nShape : ()

1D Array :
[1 2 3 4 5]\ nShape : (5,)

2D Array :
[[1 2 3]
 [4 5 6]]\ nShape : (2, 3)

3D Array :
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]\ nShape : (2, 2, 2)



In [ ]:
import numpy as np
array = np . array ([[1 , 2 , 3] , [4 , 5 , 6]]) # Shape (2 , 3)
reshaped_array = array . reshape (3 , 2) # Reshape to (3 ,) , keeping 6 elements
print (" Original Shape :", array . shape , "\ nReshaped Shape :", reshaped_array . shape )
# # Expected Outputs :
# Original Shape : (2 , 3)
# Reshaped Shape : (3 , 2)

 Original Shape : (2, 3) \ nReshaped Shape : (3, 2)


In [ ]:
import numpy as np
a = np . arange (1 , 10)
print ( a )
x = range (1 , 10)
print ( x ) # x is an iterator
print ( list ( x ) )
# further arange examples :
x = np . arange (10.4)
print ( x )
x = np . arange (0.5 , 10.4 , 0.8)
print ( x)

[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


In [ ]:
import numpy as np
arr1 = np . array ([[1 , 2] , [3 , 4]]) # Shape : (2 , 2)
arr2 = np . array ([[5 , 6] , [7 , 8]]) # Shape : (2 , 2)
# Stacking examples
hstacked = np . hstack (( arr1 , arr2 ) )
# Output hstack : [[1 2 5 6] [3 4 7 8]]
vstacked = np . vstack (( arr1 , arr2 ) )
# Output vstack [[1 2] [3 4] [5 6] [7 8]]
colstacked = np . column_stack (( arr1 [0] , arr2 [0]) )
# Output column stack : [[1 5] [2 6]]
print( hstacked , vstacked , colstacked , sep ="\n\n")

In [ ]:
import numpy as np
# 50 values between 1 and 10:
print ( np . linspace (1 , 10) )
# 7 values between 1 and 10:
print ( np . linspace (1 , 10 , 7) )
# excluding the endpoint :
print ( np . linspace (1 , 10 , 7 , endpoint = False ) )

1. Initialize an empty array with size 2X2.

In [ ]:
import numpy as np

empty_array = np.empty((2, 2))
print(empty_array)

[[4.99772206e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]


2. Initialize an all one array with size 4X2.

In [ ]:
import numpy as np

ones_array = np.ones((4, 2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
import numpy as np

fill_value_array = np.full((3, 3), 3)
print(fill_value_array)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
import numpy as np

given_array = np.array([[4, 5, 1], [8, 3, 9]])
zeros_like_array = np.zeros_like(given_array)
print(zeros_like_array)

[[0 0 0]
 [0 0 0]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
import numpy as np

given_array = np.array([[10, 20, 30], [40, 50, 60]])
ones_like_array = np.ones_like(given_array)

print(ones_like_array)

[[1 1 1]
 [1 1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print(numpy_array)

[1 2 3 4]


**4.1.1 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:**

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
import numpy as np

array_range = np.arange(10, 50)
print(array_range)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [ ]:
import numpy as np

array = np.arange(9)
matrix = array.reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
import numpy as np

identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [ ]:
import numpy as np
random_array = np.random.random(30) #random.random(size) generate number between 0 and 1.
mean_value = random_array.mean()

print("Random Array:", random_array)
print("Mean of the Array:", mean_value)

Random Array: [0.18449895 0.69539408 0.91049485 0.76522678 0.66893615 0.53398146
 0.40154306 0.94866648 0.40279748 0.9959159  0.27144545 0.02837225
 0.55325234 0.99482    0.91597912 0.82101091 0.38260613 0.07532685
 0.68676981 0.11867665 0.16809472 0.06527527 0.48579181 0.71887692
 0.42658441 0.86999945 0.46030955 0.11800351 0.98679246 0.83601882]
Mean of the Array: 0.5497153877052549


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
import numpy as np

random_array = np.random.random((10, 10))

min_value = random_array.min()
max_value = random_array.max()

print("Random Array:", random_array)
print(random_array)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)


Random Array: [[3.41244233e-02 8.60566471e-01 8.72531737e-01 9.03090312e-01
  7.40548700e-01 7.76378459e-01 8.84734332e-01 9.38726679e-01
  9.46648231e-01 2.46203011e-01]
 [7.80137510e-01 8.26082900e-01 1.83563663e-01 3.24915975e-01
  2.44527918e-01 9.35574737e-01 6.48228007e-02 6.47565048e-01
  9.48189151e-01 6.51566527e-01]
 [7.36237116e-01 3.39828114e-01 5.24194370e-02 2.63439345e-02
  1.78724865e-04 9.23399379e-01 4.93743942e-03 7.01706384e-01
  8.73839255e-01 3.50706624e-01]
 [3.32404278e-01 3.13984444e-01 3.97839775e-01 8.59622717e-01
  7.98657029e-01 3.99525307e-01 4.28670449e-01 6.75857983e-03
  3.89795716e-01 9.93565379e-02]
 [8.91499931e-01 9.78002013e-01 2.65803104e-01 2.25984863e-01
  4.95946058e-01 8.68871727e-01 9.48565359e-01 9.93998352e-01
  6.31873491e-01 7.22155783e-01]
 [8.94847182e-02 6.02123735e-01 4.22856986e-01 1.59815148e-01
  7.42697631e-03 9.33545749e-01 1.48900922e-01 3.16368448e-01
  5.98483983e-01 5.70933222e-01]
 [9.28400314e-01 7.99915412e-01 6.30446120e-

6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
import numpy as np

zero_array = np.zeros(10)
zero_array[4] = 1

print(zero_array)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
import numpy as np

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_array = arr[::-1] # we can reverse using slicing method where arr[::-1] -1 will reverse the order

print(reversed_array)

[0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
import numpy as np

array = np.ones((3, 3))
array[1:-1, 1:-1] = 0

print(array)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

checkerboard = np.zeros((8, 8))

checkerboard[1::2, ::2] = 1  # It will set 1's at every other column starting from row 1
checkerboard[::2, 1::2] = 1  # It will set 1's at every other row starting from column 1

print(checkerboard)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


**Problem - 3: Array Operations:**

For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:

In [ ]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays (x + y, v + w)
add_result_xy = x + y
print("Addition of x and y:")
print(add_result_xy)

add_result_vw = v + w
print("Addition of v and w:")
print(add_result_vw)

# 2. Subtract the two arrays (x - y, v - w)
subtract_result_xy = x - y
print("Subtraction of x and y:")
print(subtract_result_xy)

subtract_result_vw = v - w
print("Subtraction of v and w:")
print(subtract_result_vw)


Addition of x and y:
[[ 6  8]
 [10 13]]
Addition of v and w:
[20 22]
Subtraction of x and y:
[[-4 -4]
 [-4 -3]]
Subtraction of v and w:
[-2 -2]


3. Multiply the array with any integers of your choice.

In [ ]:
import numpy as np

x_multiplied = x * 2
print("x multiplied by 2:")
print(x_multiplied)

v_multiplied = v * 4
print("v multiplied by 4:")
print(v_multiplied)

x multiplied by 2:
[[ 2  4]
 [ 6 10]]
v multiplied by 4:
[36 40]


4. Find the square of each element of the array.

In [ ]:
import numpy as np

x_squared = x ** 2
y_squared = y ** 2
v_squared = v ** 2
w_squared = w ** 2


print("Squared elements of x:", x_squared)
print("Squared elements of y:", y_squared)
print("Squared elements of v:", v_squared)
print("Squared elements of w:", w_squared)

Squared elements of x: [[ 1  4]
 [ 9 25]]
Squared elements of y: [[25 36]
 [49 64]]
Squared elements of v: [ 81 100]
Squared elements of w: [121 144]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
import numpy as np
# We can find dot product using np.dot(array1 , array2) function
dot_vw = np.dot(v, w)
print("Dot product of v and w:", dot_vw)

dot_xv = np.dot(x, v)
print("Dot product of x and v:", dot_xv)

dot_xy = np.dot(x, y)
print("Dot product of x and y:", dot_xy)


Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y: [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
import numpy as np
# We can use np.concatenate((array1, array2), axis=0) where axis 0 will concatenate along rows
concat_xy_rows = np.concatenate((x, y), axis=0)
print("Concatenated x and y along rows:")
print(concat_xy_rows)

#  We need to first reshape v and w into column vectors
v_col = v.reshape(-1, 1)
w_col = w.reshape(-1, 1)

# We can use np.concatenate((array1, array2), axis=1) where axis 1 will concatenate along columns
concat_vw_columns = np.concatenate((v_col, w_col), axis=1)
print("Concatenated v and w along columns:")
print(concat_vw_columns)

Concatenated x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenated v and w along columns:
[[ 9 11]
 [10 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

Ans: I got an error because v and x didn't have matching dimensions
Fixing the error by reshaping v to match x's dimensions

In [4]:
v_reshaped = [np.newaxis, :]  # Reshape v to (1, 2)
concat_xv_fixed = np.concatenate((x, v_reshaped), axis=0)
print("\nConcatenation of x and reshaped v:\n", concat_xv_fixed)

SyntaxError: invalid syntax (<ipython-input-4-398ab7c22f12>, line 1)

**Problem - 4: Matrix Operations:**

• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)
T = BTAT

In [6]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inv = np.linalg.inv(A)

result_identity = np.dot(A, A_inv) #Multiplying A matrix and A inverse matrix

print("A * A^-1:")
print(result_identity)


A * A^-1:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


Prove AB ̸= BA.

In [8]:
AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB:")
print(AB)

print("BA:")
print(BA)

# Check if AB equals BA
are_equal = np.array_equal(AB, BA)
print("AB = BA:", are_equal)


AB:
[[23 13]
 [51 29]]
BA:
[[36 44]
 [13 16]]
AB = BA: False


3. Prove (AB)T=BTAT(AB)T=BTAT:


In [10]:
AB_transpose = np.transpose(np.dot(A, B))

B_transpose = np.transpose(B)
A_transpose = np.transpose(A)

BT_AT = np.dot(B_transpose, A_transpose)

print("(AB)^T:")
print(AB_transpose)

print("B^T A^T:")
print(BT_AT)

are_transposes_equal = np.array_equal(AB_transpose, BT_AT)
print("(AB)^T = B^T A^T:", are_transposes_equal)


(AB)^T:
[[23 51]
 [13 29]]
B^T A^T:
[[23 51]
 [13 29]]
(AB)^T = B^T A^T: True


• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

In [13]:
import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

det_A = (A[0, 0] * (A[1, 1] * A[2, 2] - A[1, 2] * A[2, 1]) -
         A[0, 1] * (A[1, 0] * A[2, 2] - A[1, 2] * A[2, 0]) +
         A[0, 2] * (A[1, 0] * A[2, 1] - A[1, 1] * A[2, 0]))

print("Determinant of A:", det_A)

cofactor_matrix = np.array([
    [(A[1, 1] * A[2, 2] - A[1, 2] * A[2, 1]), -(A[1, 0] * A[2, 2] - A[1, 2] * A[2, 0]), (A[1, 0] * A[2, 1] - A[1, 1] * A[2, 0])],
    [-(A[0, 1] * A[2, 2] - A[0, 2] * A[2, 1]), (A[0, 0] * A[2, 2] - A[0, 2] * A[2, 0]), -(A[0, 0] * A[2, 1] - A[0, 1] * A[2, 0])],
    [(A[0, 1] * A[1, 2] - A[0, 2] * A[1, 1]), -(A[0, 0] * A[1, 2] - A[0, 2] * A[1, 0]), (A[0, 0] * A[1, 1] - A[0, 1] * A[1, 0])]
])
adjoint_A = cofactor_matrix.T
inverse_A = adjoint_A / det_A
print("\nInverse of A:\n", inverse_A)
X = np.dot(inverse_A, B)
print("\nSolution (x, y, z):", X)

Determinant of A: -19

Inverse of A:
 [[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]

Solution (x, y, z): [ 2.  1. -2.]


• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [15]:

A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

print("Solution for [x, y, z]:")
print(X)


Solution for [x, y, z]:
[ 2.  1. -2.]


4.2 Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:

1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [19]:
import numpy as np
import time

size = 1_000_000
list1 = [i for i in range(1_000_000)]
list2 = [i for i in range(1_000_000)]
start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(len(list1))]
end_time = time.time()
print(f"Time taken by Python Lists: {end_time - start_time:.5f} seconds")

array1 = np.array(list1)
array2 = np.array(list2)

start_time = time.time()
result_array = array1 + array2
end_time = time.time()
print(f"Time taken by numpy: {end_time - start_time:.5f} seconds\n")


Time taken by Python Lists: 0.16674 seconds
Time taken by numpy: 0.00250 seconds



2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [21]:
start_time = time.time()
list_product = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()
list_time = end_time - start_time
print(f"Time taken using Python lists: {list_time:.5f} seconds")

start_time = time.time()
array_product = array1 * array2
end_time = time.time()
numpy_time = end_time - start_time
print(f"Time taken using NumPy arrays: {numpy_time:.5f} seconds")

Time taken for multiplication using Python lists: 0.169287 seconds
Time taken for multiplication using NumPy arrays: 0.004890 seconds


3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays,

In [22]:
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))
end_time = time.time()
list_time = end_time - start_time
print(f"Dot product using Python lists: {dot_product_list}")
print(f"Time taken for dot product using Python lists: {list_time:.6f} seconds")

start_time = time.time()
dot_product_numpy = np.dot(array1, array2)
end_time = time.time()
numpy_time = end_time - start_time
print(f"Dot product using NumPy arrays: {dot_product_numpy}")
print(f"Time taken for dot product using NumPy arrays: {numpy_time:.6f} seconds")

Dot product using Python lists: 333332833333500000
Time taken for dot product using Python lists: 0.278353 seconds
Dot product using NumPy arrays: 333332833333500000
Time taken for dot product using NumPy arrays: 0.002050 seconds


4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [ ]:

size = 1000
list_matrix1 = [[j for j in range(size)] for i in range(size)]
list_matrix2 = [[j for j in range(size)] for i in range(size)]

numpy_matrix1 = np.array(list_matrix1)
numpy_matrix2 = np.array(list_matrix2)

start_time = time.time()
list_result = [[sum(list_matrix1[i][k] * list_matrix2[k][j] for k in range(size)) for j in range(size)] for i in range(size)]
end_time = time.time()
list_time = end_time - start_time
print(f"Time taken for matrix multiplication using Python lists: {list_time:.6f} seconds")

start_time = time.time()
numpy_result = np.dot(numpy_matrix1, numpy_matrix2)
end_time = time.time()
numpy_time = end_time - start_time
print(f"Time taken for matrix multiplication using NumPy arrays: {numpy_time:.6f} seconds")

# It took to much time and it didn't compile teh output
